name: 'download translations'
on:
  push:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: macos
    name: test download action
    steps:
      - uses: locize/download@v1
        with:
          project-id: 95050b13-fe3a-4288-bfe3-e40eaf11b82b
          format: yaml
      - run: ls -al locales/en
 
