name: 'Upload translations'
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: SimpleLocalize Upload
        uses: simplelocalize/upload@2.0
        with:
          apiKey: 8486d121-63d7-4063-aaf1-c7f40a6180e3
          uploadPath: ./locales/en/Trial.json
          uploadFormat: json
