on:
  push:
    branches: [main]
  repository_dispatch:
    types: [locize/versionPublished]

jobs:
  test1:
    name: Test1 (conditional run)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
         apiKey: 8486d121-63d7-4063-aaf1-c7f40a6180e3
      - run: 'echo "field: ${{ github.event.client_payload.payload.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - run: echo baz
        if: github.event.client_payload.payload.version == 'latest'
     
  test2:
    name: Test2 (conditional step)
    if: github.event.client_payload.payload.version == 'latest'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.payload.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
