on:
  push:
    branches: [master]
  repository_dispatch:
    types: [locize/versionPublished]

jobs:
 
      
  test3:
    name: Test3
    runs-on: macos-latest
    steps:
      - uses: locize/download@v1
        with:
         project-id: 95050b13-fe3a-4288-bfe3-e40eaf11b82b
         api-key: 7fd1b519-a115-4cd0-9465-28f4dbc3e920
         
  test1:
     name: Commit & Push changes
     runs-on: macos-latest
     steps:
      - uses: actions/checkout@master
      - uses: actions-js/push@master
        with:
         persist-credentials: false 
         fetch-depth: 0 
         github_token: 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
     
 
         
