on:
  push:
    branches: [master]
  repository_dispatch:
    types: [locize/versionPublished]
    with:
     project-id: 1ad6f6ce-50cf-4848-ab09-81cc6e120177

jobs:
  test1:
    name: Test1 (conditional run)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.payload.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - run: echo baz
        if: github.event.client_payload.payload.version == 'latest'
  test2:
    name: Test2 (conditional step)
    if: github.event.client_payload.payload.version == 'latest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "field: ${{ github.event.client_payload.payload.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
