name: 'download translations'
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test1 (conditional run)
        uses: locize/download@v1
        with:
          project-id: 95050b13-fe3a-4288-bfe3-e40eaf11b82b
          api-key: 7fd1b519-a115-4cd0-9465-28f4dbc3e920
          path-mask: /public/locales
      
