name: 'download translations'
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test1 (conditional run)
        uses: locize/download@v1
        with:
          project-id: 95050b13-fe3a-4288-bfe3-e40eaf11b82b
      
